### ISSUE TITLE
 Can the kernel enable Android Docker related configurations by default

### ISSUE THREAD

**Issue by kingwho** [radxa-pkg/linux-rockchip#1]
![image](https://github.com/radxa-pkg/linux-rockchip/assets/42891215/92e924d7-5437-4ed9-aece-a771b275bcf0)

**Comment by kingwho** [comment]
![image](https://github.com/radxa-pkg/linux-rockchip/assets/42891215/25d10161-ab32-47b1-b6da-13b7bbbc2880)

**Comment by RadxaYuntian** [comment]
The first 3 options are already enabled. I can enable PSI for our future kernel.
